.\"
.\" surf API / surf_init man page
.\" Copyright (c) 2022 Dylan Eskew, Stephen Loudiana, Kevin McGrane
.\" * This software is under the terms of the BSD license.  * See README for more details.
.\"
.Dd April 5, 2022
.Dt SURF_INIT
.Os
.Sh NAME
.Nm surf_init
.Nd initialize the surf api to connect to a running instance of
.Xr wpa_supplicant 8
.Sh LIBRARY
Surf Library (libsurf, -lsurf)
.Sh SYNOPSIS
.In "surf.h"
.Ft int
.Fn surf_init "void"
.Sh DESCRIPTION
The
.Fn surf_init
function initialzes a connection with a running instance
.Xr wpa_supplicant 8
and prepares the environment for interaction with it.
.Sh RETURN VALUES
.Fn surf_init
will return 0 on success and a -1 on failure.
.Sh SEE ALSO
.Xr surf 3  ,
.Xr surf_conf 3 ,
.Xr surf_list 3 ,
.Xr wpa_supplicant 8 ,
.Xr wpa_supplicant.conf 5
.Sh AUTHORS
.An Dylan Eskew
